### ISSUE TITLE
Step 5. systrace.py not working on Windows

### ISSUE THREAD

**Issue by Magolac** [googlecodelabs/android-perf-testing#11]
Executing systrace.py on Windows 7 produces the following exception:
Traceback (most recent call last):
  File "systrace-legacy.py", line 251, in <module> main()
  File "systrace-legacy.py", line 157, in main
    ready = select.select([adb.stdout, adb.stderr], [], [adb.stdout, adb.stderr]
)
select.error: (10093, 'Either the application has not called WSAStartup, or WSAS
tartup failed')

Is there any way to execute the script systrace.py on Windows from command line?

**Comment by PaulRashidi** [comment]
Yes, try running it with the MonkeyRunner wrapper first. Print the arguments from this [method invocation](https://github.com/googlecodelabs/android-perf-testing/blob/master/buildSrc/src/main/groovy/com/google/android/perftesting/RunLocalPerfTestsTask.groovy#L72) and run that on your command line. If that doesn't surface the issue then [print this command](https://github.com/googlecodelabs/android-perf-testing/blob/master/run_perf_tests.py#L61) and then run that from your command line. We had tested this with a few versions of Windows before, but there may be a regression which we need to fix.

**Comment by PaulRashidi** [comment]
Curious if you were able to get back to this? If I don't see a response in about a week I'll assume you got it to work. Thanks!

**Comment by PaulRashidi** [comment]
The Systrace listed in this codelab doesn't work on Windows it would seem, I've noted in an issue that that should be updated.
