### ISSUE TITLE
When running runLocalPerfTests nothing happens

### ISSUE THREAD

**Issue by pulse1989** [googlecodelabs/android-perf-testing#18]
Should i be seeing the espresso tests at this point? because I don't see this. all i see is the list of tests completing and the reports aren't even generated. 

However running the tests with the commands work. 

![alt tag] (http://i.imgur.com/I29NOB5.jpg)

**Comment by pulse1989** [comment]
issue sorted

**Comment by kashban** [comment]
And exactly how did you sort this out? 

Geez, why are people doing this: Stating a problem and later that they solved it but not how? Please think of other developers that might have the same issue when closing tickets.
