### ISSUE TITLE
How to implement @PerfTest annotation in my projects?

### ISSUE THREAD

**Issue by piotrek1543** [googlecodelabs/android-perf-testing#5]
Hi,

I've already noticed that it is custom annotation created only for this project. I relly like it and I've found it pretty useful. Could you tell me the easiest way to use it in my apps tests?

Cheers

**Comment by PaulRashidi** [comment]
When we invoke the tests in the monkeyrunner script we specify the annotation so that only those tests are run: https://github.com/googlecodelabs/android-perf-testing/blob/master/run_perf_tests.py#L43

**Comment by piotrek1543** [comment]
@PaulRashidi, thanks for answer.
